# Generated by Django 5.0.6 on 2024-06-10 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('floor', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('equipment', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom_info_by_time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.classroom')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.time')),
            ],
            options={
                'unique_together': {('classroom', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Classroom_availibility_by_time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availibility', models.BooleanField(default=True)),
                ('classroom_info_by_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.classroom_info_by_time_slot')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.classroom_availibility_by_time_slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.student')),
            ],
        ),
    ]
