# Generated by Django 5.0.6 on 2024-06-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_student_password_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='classroom_availability',
        ),
        migrations.AddField(
            model_name='classroom_info_by_time_slot',
            name='availibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='classroom_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.classroom_info_by_time_slot'),
        ),
        migrations.DeleteModel(
            name='Classroom_availibility_by_time_slot',
        ),
    ]
