# Generated by Django 5.0.6 on 2024-06-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_classroom_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
